<div class="container">
      
      <div class="hero-unit-home">
        <div class="row">
            <div class="span12">
              <div class="row show-grid">
                <div class="span12">
                  Titulo Titulo Titulo Titulo Titulo Titulo Titulo Titulo 
                </div>
              </div>
              <div class="row">
                <div class="span5 mini-layout">
                  <div class="counterBox">
                        
                            <div id="myCarousel" class="carousel slide">
                              <div class="carousel-inner">
                                <div class="item active">
                                  <img src="../resources/img/bootstrap-mdo-sfmoma-01.jpg" alt="">
                                </div>
                                <div class="item">
                                  <img src="../resources/img/bootstrap-mdo-sfmoma-02.jpg" alt="">
                                </div>
                                <div class="item">
                                  <img src="../resources/img/bootstrap-mdo-sfmoma-03.jpg" alt="">
                                </div>
                              </div>
                              <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                              <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
                            </div>
                          
                  </div>
                </div>
                <div class="span6 mini-layout">
                  <div class="counterBox">
                        Descripcion
                  </div>
                </div>
              
              </div>
            </div>
        </div>
        <div class="row show-grid">
            <div class="span6 offset3">
              Comentarios
            </div>
          </div>
      </div>