  <div class="container">

    <!-- Docs nav
    ================================================== -->
    <div class="row">
      <div class="span-menu bs-docs-sidebar">
        <ul class="nav nav-list bs-docs-sidenav">
        	<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
			<li><a href="#categoria"><i class="icon-chevron-right"></i> Categoria</a></li>
        </ul>
      </div>
      <div class="span9">

        <section id="products">
          


<div class="prettyprint ">
<h5>Lista de Productos</h5>
                        	<ul class="thumbnails">
								<li class="span2">
									<div class="thumbnail">
								    	<img src="../resources/img/bootstrap-mdo-sfmoma-02.jpg" alt="">
								    	<dl>
											<dt>Producto</dt>
										  	<dd>$12345</dd>
										  	<dd>$12345</dd>
										</dl>
								    </div>
								</li>
								<li class="span2">
									<div class="thumbnail">
								    	<img src="../resources/img/bootstrap-mdo-sfmoma-02.jpg" alt="">
								    	<dl>
											<dt>Producto</dt>
										  	<dd>$12345</dd>
										  	<dd>$12345</dd>
										</dl>
								    </div>
								</li>
								<li class="span2">
									<div class="thumbnail">
								    	<img src="../resources/img/bootstrap-mdo-sfmoma-02.jpg" alt="">
								    	<dl>
											<dt>Producto</dt>
										  	<dd>$12345</dd>
										  	<dd>$12345</dd>
										</dl>
								    </div>
								</li>
								<li class="span2">
									<div class="thumbnail">
								    	<img src="../resources/img/bootstrap-mdo-sfmoma-02.jpg" alt="">
								    	<dl>
											<dt>Producto</dt>
										  	<dd>$12345</dd>
										  	<dd>$12345</dd>
										</dl>
								    </div>
								</li>
								<li class="span2">
									<div class="thumbnail">
								    	<img src="../resources/img/bootstrap-mdo-sfmoma-02.jpg" alt="">
								    	<dl>
											<dt>Producto</dt>
										  	<dd>$12345</dd>
										  	<dd>$12345</dd>
										</dl>
								    </div>
								</li>
							</ul>
</div>

          

        </section>



      </div>
    </div>

  </div>
