<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>WAZPO Fast Cart Creation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="<?php BASE_URL?>/resources/js/jquery.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-transition.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-alert.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-modal.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-dropdown.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-scrollspy.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-tab.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-tooltip.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-popover.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-button.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-collapse.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-carousel.js"></script>
    <script src="<?php BASE_URL?>/resources/js/bootstrap-typeahead.js"></script>

    <script type="text/javascript" src="<?php BASE_URL?>/resources/js/jquery.form.js"></script>   

    <!-- Le styles -->
    <link href="<?php BASE_URL?>/resources/css/bootstrap.css" rel="stylesheet">
    <link href="<?php BASE_URL?>/resources/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php BASE_URL?>/resources/css/docs.css" rel="stylesheet">
    <link href="<?php BASE_URL?>/resources/css/estilos.css" rel="stylesheet">
  

    <link href="<?php BASE_URL?>/resources/js/google-code-prettify/prettify.css" rel="stylesheet">

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="<?php BASE_URL?>/resources/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<?php BASE_URL?>/resources/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php BASE_URL?>/resources/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php BASE_URL?>/resources/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php BASE_URL?>/resources/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?php BASE_URL?>/resources/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="<?php BASE_URL?>/">Wazpo</a></li>
              <li><a href="<?php BASE_URL?>/producto">Productos</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>              
            </ul>
            <ul class="nav pull-right">
              <li class="dropdown">
                  <?php
                    if(empty($_SESSION['username']) ) {
                  ?>
                      <a href="<?php BASE_URL?>/prueba/redirect"><img src="<?php BASE_URL?>/resources/img/lighter.png" alt="Sign in with Twitter"/></a>
                  <?php
                    } else {
                  ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <img src="<?=$this->userContent->profile_image_url?>" width="20" height="20"> <?=$this->userContent->screen_name?> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="<?php BASE_URL?>/user/account">Mi cuenta</a></li>
                      <li><a href="<?php BASE_URL?>/user/messages">Mensajes (#)</a></li>
                      <li><a href='<?php BASE_URL?>/user/clearsessions'>Salir</a></li>
                      <li class="divider"></li>
                      <li class="nav-header">Tienda</li>
                      <li><a href='<?php BASE_URL?>/user/products'>Mis Productos</a></li>
                      <li><a href='<?php BASE_URL?>/user/addproduct'>Ingresar Productos</a></li>
                      <li><a href="<?php BASE_URL?>/user/whishlist">Productos Favoritos</a></li>
                    </ul>
                  <?php
                    }
                  ?>
              </li>
            </ul>            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

	<?=$this->content();?>
	
  </div>
  <div class="container">
	 <hr>

      <footer>
        <p>&copy; Wazpo 2012</p>
      </footer>

    </div> <!-- /container -->
	  
	</body>
</html>
